[world]
width = 15
height = 10

[herbivore]
health = 10
speed = 2

[predator]
health = 10
speed = 2
attack_power = 3

[spawn_limit]
predator = 10
herbivore = 10
tree = 10
grass = 10
rock = 10

[icons]
predator = "ğŸº "
herbivore = "ğŸ‡ "
grass = "ğŸŒ¿ "
rock = "ğŸª¨ "
tree = "ğŸŒ³ "
default = "ğŸŸ§ "
